### ISSUE TITLE
Playground: "TypeError: u.registerProjectFolder is not a function"

### ISSUE THREAD

**Issue by siketyan** [biomejs/website#1785]
Can't open the playground due to the error.
Firefox Developer Edition 136b9.

```
TypeError: u.registerProjectFolder is not a function
    <anonymous> https://biomejs.dev/_astro/biomeWorker-DedpHcjG.js:2
    <anonymous> https://biomejs.dev/_astro/biomeWorker-DedpHcjG.js:2
```

**Comment by siketyan** [comment]
It seems introduced in #1784
